apiVersion: v1
kind: ConfigMap
metadata:
  name: headlamp-config
  namespace: headlamp
data:
  config.json: |
    {
      "oidc": {
        "clientID": "AZURE_AD_CLIENT_ID_PLACEHOLDER",
        "issuerURL": "https://login.microsoftonline.com/TENANT_ID_PLACEHOLDER/v2.0",
        "scopes": "openid profile email"
      }
    }
