apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ria-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: ria-poc.nymbl.host
      http:
        paths:
          - path: /rest
            pathType: Prefix
            backend:
              service:
                name: ria-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ria-frontend
                port:
                  number: 80
