apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sns-forwarder
  namespace: monitoring
  labels:
    app: alertmanager-sns-forwarder
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9087
      targetPort: http
      protocol: TCP
  selector:
    app: alertmanager-sns-forwarder
