apiVersion: v1
kind: Service
metadata:
  name: ria-backend
  labels:
    app: ria-backend
spec:
  type: ClusterIP
  selector:
    app: ria-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
